In [1]:
!pip install numpy 


Defaulting to user installation because normal site-packages is not writeable



[notice] A new release of pip is available: 23.2.1 -> 24.0
[notice] To update, run: python.exe -m pip install --upgrade pip


In [2]:
import numpy as np
kanto=np.array([23.0,34.0,67.0])
weights=np.array([45,56,78])
kanto.dtype 

dtype('float64')

In [3]:
climate_data=np.array([[],[],[]])
climate_data.shape

(3, 0)

In [4]:
# 3D array
arr3 = np.array([
                [91, 88, 64],
                         [87, 134, 58],
                         [102, 43, 37],
                         [69, 96, 70]])
weights=np.array([0.3,0.2,0.5])

a=np.matmul(arr3,weights)
print(a)

[76.9 81.9 57.7 74.9]


In [5]:
arr3 = np.array([
                [91, 88, 64],
                         [87, 134, 58],
                         [102, 43, 37],
                         [69, 96, 70]])
weights=np.array([0.3,0.2,0.5])
print(arr3@weights)

[76.9 81.9 57.7 74.9]


### Working with CSV data files

In [6]:
import numpy as np
import urllib.request
urllib.request.urlretrieve('https://gist.github.com/BirajCoder/a4ffcb76fd6fb221d76ac2ee2b8584e9/raw/4054f90adfd361b7aa4255e99c2e874664094cea/climate.csv', 
    'climate.txt')

climate_data=np.genfromtxt("climate.txt",delimiter=",", skip_header=1)
weights=np.array([0.3,0.2,0.5])
yields=climate_data@weights
yields.shape

(10000,)

In [7]:
climate_data

array([[25., 76., 99.],
       [39., 65., 70.],
       [59., 45., 77.],
       ...,
       [99., 62., 58.],
       [70., 71., 91.],
       [92., 39., 76.]])

In [8]:
climate_result=np.concatenate((climate_data,yields.reshape(10000,1)),axis=1)
climate_result

array([[25. , 76. , 99. , 72.2],
       [39. , 65. , 70. , 59.7],
       [59. , 45. , 77. , 65.2],
       ...,
       [99. , 62. , 58. , 71.1],
       [70. , 71. , 91. , 80.7],
       [92. , 39. , 76. , 73.4]])

In [9]:
np.savetxt("climate_result.txt",climate_result,fmt="%2f",delimiter=",",header='temperature,rainfall,humidity,yeild_apples', comments=" ")

In [10]:
climate_results=np.genfromtxt("climate_result.txt",
                              delimiter=",")

In [11]:
climate_result.shape

(10000, 4)

#### Operation on arrays


In [12]:
arr2 = np.array([[1, 2, 3, 4], 
                 [5, 6, 7, 8], 
                 [9, 1, 2, 3]])
 
arr3= np.array([[11, 12, 13, 14], 
                 [15, 16, 17, 18], 
                 [19, 11, 12, 13]])

arr5= arr2%4
arr5

array([[1, 2, 3, 0],
       [1, 2, 3, 0],
       [1, 1, 2, 3]], dtype=int32)

In [13]:
arr4 = np.array([4, 5, 6, 7])
arr2==arr5

array([[ True,  True,  True, False],
       [False, False, False, False],
       [False,  True,  True,  True]])

In [14]:
arr3 = np.array([
    [[11, 12, 13, 14], 
     [13, 14, 15, 19]], 
    
    [[15, 16, 17, 21], 
     [63, 92, 36, 18]], 
    
    [[98, 32, 81, 23],      
     [17, 18, 19.5, 43]]])

arr3[[0],[1],[2]]

array([15.])

In [15]:
#subarrays_using arrays
sarr=arr3[1:,0:1,1:2]
sarr

array([[[16.]],

       [[32.]]])

In [16]:
np.random.rand(5,4)

array([[0.69871487, 0.97957948, 0.650072  , 0.45923816],
       [0.32575811, 0.7859661 , 0.47252859, 0.32521753],
       [0.71051326, 0.16538073, 0.71974671, 0.37151402],
       [0.57528812, 0.41829773, 0.90084932, 0.51318431],
       [0.6815731 , 0.75559527, 0.83388463, 0.01593195]])

In [17]:
np.full([2,3],42)

array([[42, 42, 42],
       [42, 42, 42]])

In [18]:
np.linspace(3,27,9)


array([ 3.,  6.,  9., 12., 15., 18., 21., 24., 27.])

the numpy version and the configuration

In [19]:
import numpy as np
print(np.__version__)
print(np.show_config)

1.26.4
<function show at 0x0000027AE8F849A0>


In [20]:
import numpy as np 
#creating a null vecot of size 10
x=np.zeros(10)
y=np.random.random((10,10))
z=np.min(y)
print(y,z)
    

[[0.94953885 0.69790937 0.66144126 0.70274445 0.13258703 0.58423046
  0.6355819  0.19884717 0.1477805  0.85527749]
 [0.38989249 0.74995225 0.33325327 0.07346016 0.89167457 0.91454867
  0.03867934 0.98379742 0.0110087  0.00507964]
 [0.7229142  0.48991254 0.74503847 0.93053727 0.24522757 0.85044717
  0.43451287 0.78264168 0.79350479 0.09238869]
 [0.39843757 0.73617017 0.01874052 0.50396421 0.48578443 0.63318472
  0.88187631 0.57823352 0.7523957  0.67716601]
 [0.32919814 0.60359351 0.03904588 0.42800061 0.2056275  0.60459807
  0.45054057 0.42498777 0.19744627 0.67718261]
 [0.47450657 0.54234705 0.35347975 0.78052052 0.01227855 0.39766375
  0.32265401 0.00158165 0.75794773 0.02709509]
 [0.22610772 0.88676882 0.5157118  0.36340147 0.08238152 0.90309061
  0.01970562 0.95245321 0.85666095 0.17037547]
 [0.11249878 0.552371   0.93716167 0.98627108 0.1046891  0.41739218
  0.93012556 0.20794155 0.58082716 0.62261601]
 [0.26370505 0.38298814 0.16520454 0.34804028 0.55511626 0.44138386
  0.17332134

In [21]:
#How to add a border (filled with 0's) around an existing array?

import numpy as np 
existing_array=np.array([[1,2,3],
                         [4,5,6],
                         [7,8,9]])
rows,columns=existing_array.shape
newarray=np.zeros((rows+2,columns+2))
newarray[1:-1,1:-1]=existing_array
newarray

array([[0., 0., 0., 0., 0.],
       [0., 1., 2., 3., 0.],
       [0., 4., 5., 6., 0.],
       [0., 7., 8., 9., 0.],
       [0., 0., 0., 0., 0.]])

In [22]:
#Chessboard pattern
chessboard_matrix=np.zeros((8,8),dtype=int)
chessboard_matrix[1::2,1::2]=1
chessboard_matrix[::2,::2]=1
chessboard_matrix

array([[1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1]])

In [23]:
import numpy as np
flat_index=99
shape=(6,7,8)
index_xyz=np.unravel_index(99,shape)
index_xyz

(1, 5, 3)

In [24]:
# Given a 1D array, negate all elements which are between 3 and 8, in place.
import numpy as np
array=np.array([1,4,5,6,8,10])
array[(array > 3) & (array<8)]*=-1
array

array([ 1, -4, -5, -6,  8, 10])

In [25]:
import numpy as np
np.sqrt(-1)==np.emath.sqrt(-1)

C:\Users\Sagar Bisht\AppData\Local\Temp\ipykernel_7744\4230900462.py:2: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(-1)==np.emath.sqrt(-1)


False

In [26]:
from datetime import datetime, timedelta

today=datetime.now().date()

yesterday=today-timedelta(days=1)
tomorrow=today+timedelta(days=1)

print("yesterday", yesterday)
print("today", today)
print("tomorrow", tomorrow)


yesterday 2024-05-10
today 2024-05-11
tomorrow 2024-05-12


In [27]:
from datetime import datetime, timedelta, date
start_date=date(2024,7,1)
days_in_july= 31
for i in range(days_in_july):
    july_dates=start_date+timedelta(days=i)
    print(july_dates)

2024-07-01
2024-07-02
2024-07-03
2024-07-04
2024-07-05
2024-07-06
2024-07-07
2024-07-08
2024-07-09
2024-07-10
2024-07-11
2024-07-12
2024-07-13
2024-07-14
2024-07-15
2024-07-16
2024-07-17
2024-07-18
2024-07-19
2024-07-20
2024-07-21
2024-07-22
2024-07-23
2024-07-24
2024-07-25
2024-07-26
2024-07-27
2024-07-28
2024-07-29
2024-07-30
2024-07-31


In [28]:
import numpy as np 
A=np.linspace(0,4,25)
A=A.reshape(5,5)
A

array([[0.        , 0.16666667, 0.33333333, 0.5       , 0.66666667],
       [0.83333333, 1.        , 1.16666667, 1.33333333, 1.5       ],
       [1.66666667, 1.83333333, 2.        , 2.16666667, 2.33333333],
       [2.5       , 2.66666667, 2.83333333, 3.        , 3.16666667],
       [3.33333333, 3.5       , 3.66666667, 3.83333333, 4.        ]])

In [29]:
 #Consider a generator function that generates 10 integers and use it to build an array
import numpy as np
import random
def generator_():
    list=[]
    for i in range(10):
        a=random.randint(0,100)
        list.append(a)
    array=np.array(list)
    return array
type(generator_())
     

numpy.ndarray

In [30]:
#Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)
import numpy
array=np.linspace(0,1,12)[1:-1]
array

array([0.09090909, 0.18181818, 0.27272727, 0.36363636, 0.45454545,
       0.54545455, 0.63636364, 0.72727273, 0.81818182, 0.90909091])

In [31]:
# Create a random vector of size 10 and sort it (★★☆
import random
import numpy as np
array=np.random.randn(10)
sorted=np.sort(array)
print(array)
print(sorted)

[-0.86187481  1.16957624 -1.04850704  0.67562354  0.84375992  0.96450435
 -0.58414153  0.46229945  0.48027079  1.239549  ]
[-1.04850704 -0.86187481 -0.58414153  0.46229945  0.48027079  0.67562354
  0.84375992  0.96450435  1.16957624  1.239549  ]


In [32]:
import random
import numpy as np 
cartesian_coordinates=np.random.random((10,2))
x,y=cartesian_coordinates[:,0],cartesian_coordinates[:,1]
print(x,y)
radius=np.sqrt(x**2+y**2)
angle=np.arctan2(y,x)
print(radius, angle)

[0.84351069 0.11031504 0.70228671 0.02821002 0.1237885  0.37757429
 0.66069348 0.52522442 0.69273286 0.11584955] [0.44089379 0.9985985  0.25730701 0.75133098 0.90824387 0.02990541
 0.38436749 0.14793865 0.63970978 0.28431253]
[0.95178654 1.00467326 0.74793952 0.75186039 0.91664089 0.37875675
 0.76436525 0.54566156 0.94292493 0.30700934] [0.48163365 1.46077257 0.3511961  1.53326722 1.43533665 0.07903904
 0.52690252 0.2745543  0.74562525 1.18386473]


In [33]:
#Create random vector of size 10 and replace the maximum value by 0
import numpy as np 
import random
random_vector=np.random.random(10)
index_max=np.argmax(random_vector)
print(random_vector)
random_vector[index_max]=0
print(random_vector)


[0.83551575 0.89184279 0.71233371 0.71015517 0.33760722 0.0296639
 0.71271233 0.3216803  0.75747266 0.48963531]
[0.83551575 0.         0.71233371 0.71015517 0.33760722 0.0296639
 0.71271233 0.3216803  0.75747266 0.48963531]
